"""
NeuroSAR SPICE integration — deck generation and result parsing for
ngspice / Xyce with Sky130 PDK.

This module is the bridge between NeuroSAR's ML pipeline and real
transistor-level simulation.  It is NOT required for the default
demo (which uses the synthetic generator in dataset.py), but it
provides everything needed to swap in real waveforms.

Workflow
--------
1. Call `generate_ngspice_deck()` with desired design parameters.
2. Run the deck externally:  ``ngspice -b deck.spice``
3. Call `parse_ngspice_output()` to convert raw output to NeuroSAR
   tensor format.
4. Feed the result into `SARDataset` / `build_dataloaders`.

Prerequisites
-------------
- ngspice ≥ 37 compiled with Sky130 model support, **or**
- Xyce ≥ 7.6 with Sky130 model cards.
- Sky130 PDK installed (e.g. via `volare` or `open_pdks`).
"""

import os
import textwrap
from typing import Dict, Optional

import numpy as np

from src.config import DESIGN, DATA_SPICE
from src.utils import ensure_dir


# =========================================================================
# Deck generation
# =========================================================================

def generate_ngspice_deck(
    vin: float = 0.9,
    vref: float = 1.8,
    cu_fF: float = 10.0,
    n_bits: int = 10,
    sim_time_ns: float = 100.0,
    corner: str = "tt",
    temp_c: float = 27.0,
    output_dir: Optional[str] = None,
) -> str:
    """
    Generate an ngspice transient deck for a SAR ADC front-end
    using Sky130 device models.

    The generated deck instantiates:
      - A binary-weighted capacitor DAC (ideal caps),
      - A StrongARM-style comparator (behavioural subcircuit),
      - SAR logic via a Verilog-A or PWL stimulus.

    Returns the path to the written .spice file.
    """
    output_dir = output_dir or ensure_dir(DATA_SPICE)
    deck_path = os.path.join(output_dir, f"sar_adc_{corner}.spice")

    cu_value = f"{cu_fF}f"
    total_cap = f"{cu_fF * (2**n_bits)}f"

    deck = textwrap.dedent(f"""\
    * ================================================================
    * NeuroSAR — Sky130 SAR ADC Front-End Transient Deck
    * Corner: {corner}  |  Temp: {temp_c}°C  |  Vin: {vin} V
    * Auto-generated by neurosar.simulate_spice
    * ================================================================

    .title SAR_ADC_FRONTEND_{corner}

    * --- Sky130 model include (adjust path to your installation) ------
    * .lib "$PDK_ROOT/sky130A/libs.tech/ngspice/sky130.lib.spice" {corner}
    * Uncomment the line above and set $PDK_ROOT for real simulation.

    * --- Parameters ---------------------------------------------------
    .param vdd   = {vref}
    .param vin_dc = {vin}
    .param cu    = {cu_value}
    .param nbits = {n_bits}
    .param temp  = {temp_c}

    * --- Supply -------------------------------------------------------
    Vdd  vdd  gnd  DC {{vdd}}
    Vss  gnd  0    DC 0

    * --- Input stimulus -----------------------------------------------
    Vin  vin  gnd  DC {{vin_dc}}

    * --- Binary-weighted capacitor array (simplified) -----------------
    * MSB cap = 2^(n-1) * Cu, ... , LSB cap = Cu
    """)

    # Add capacitor instances
    for k in range(n_bits):
        weight = 2 ** (n_bits - 1 - k)
        cap_val = f"{{cu*{weight}}}"
        deck += f"    C{k}  dac_p  sw_{k}  {cap_val}\n"

    deck += textwrap.dedent(f"""\

    * --- Parasitic load -----------------------------------------------
    Cload  dac_p  gnd  100f

    * --- Comparator (behavioural) -------------------------------------
    * Replace with a transistor-level StrongARM for full accuracy.
    .subckt comparator inp inn outp outn vdd gnd
      Einp  mid  gnd  inp inn  4.0
      Gregen outp outn mid gnd  1m
      Cout  outp outn  50f
    .ends comparator

    Xcomp  dac_p  vcm  comp_p  comp_n  vdd  gnd  comparator

    Vcm  vcm  gnd  DC {{vdd/2}}

    * --- Transient analysis -------------------------------------------
    .tran 0.01n {sim_time_ns}n

    * --- Output -------------------------------------------------------
    .control
      run
      wrdata {os.path.join(output_dir, 'tran_output.csv')} \\
        v(dac_p) v(comp_p) v(comp_n)
      quit
    .endc

    .end
    """)

    with open(deck_path, "w") as f:
        f.write(deck)

    print(f"[NeuroSAR] ngspice deck written → {deck_path}")
    return deck_path


# =========================================================================
# Output parsing
# =========================================================================

def parse_ngspice_output(
    csv_path: str,
    n_bits: int = DESIGN.n_bits,
) -> Dict[str, np.ndarray]:
    """
    Parse ngspice `.wrdata` CSV into numpy arrays.

    Expected format (space-separated, header line starting with '#'):
        # time  v(dac_p)  v(comp_p)  v(comp_n)

    Returns dict with keys: time_s, vdac, vcomp_p, vcomp_n, vdiff
    """
    raw = np.loadtxt(csv_path, comments="#")

    if raw.ndim == 1:
        raise ValueError("Parsed array is 1-D — check ngspice output format.")

    result = {
        "time_s":  raw[:, 0],
        "vdac":    raw[:, 1],
        "vcomp_p": raw[:, 2] if raw.shape[1] > 2 else np.zeros_like(raw[:, 0]),
        "vcomp_n": raw[:, 3] if raw.shape[1] > 3 else np.zeros_like(raw[:, 0]),
    }
    result["vdiff"] = result["vcomp_p"] - result["vcomp_n"]

    print(f"[NeuroSAR] Parsed {len(result['time_s'])} time points from {csv_path}")
    return result


# =========================================================================
# Batch sweep helper
# =========================================================================

def generate_sweep_decks(
    vin_values: np.ndarray,
    cu_fF_values: np.ndarray,
    output_dir: Optional[str] = None,
) -> list:
    """
    Generate a grid of ngspice decks sweeping Vin and Cu.
    Returns list of deck file paths.
    """
    paths = []
    for vin in vin_values:
        for cu in cu_fF_values:
            p = generate_ngspice_deck(
                vin=float(vin),
                cu_fF=float(cu),
                output_dir=output_dir,
            )
            paths.append(p)
    print(f"[NeuroSAR] Generated {len(paths)} sweep decks.")
    return paths
