"""
vga_flow.py - simulation harness for the subthreshold current-steering VGA core.

Everything the notebook measures goes through this module, so every number in the
notebook is regenerated by code, never typed by hand.
SPDX-License-Identifier: Apache-2.0
"""
from __future__ import annotations
import os, re, subprocess, tempfile, json, math
from pathlib import Path
import numpy as np
_trapz = getattr(np, 'trapezoid', None) or getattr(np, 'trapz')

# --------------------------------------------------------------------------- paths
PDK_ROOT = Path(os.environ.get("PDK_ROOT", "/foss/pdks"))
PDK_LIB  = PDK_ROOT / "sky130A/libs.tech/ngspice/sky130.lib.spice"
WORK     = Path(os.environ.get("VGA_WORK", tempfile.gettempdir())) / "vga_flow_work"
WORK.mkdir(parents=True, exist_ok=True)
(WORK / ".spiceinit").write_text("set ngbehavior=hsa\nset ng_nomodcheck\n")

SIM_OPTS = ".options reltol=1e-4 abstol=1e-15 vntol=1e-9 gmin=1e-15 method=gear"
K_B, Q = 1.380649e-23, 1.602176634e-19

# --------------------------------------------------------------------------- design
BASELINE = dict(            # the hand-sized Phase-1 point
    W_in=20.0, L_in=1.0,    # M2, M3   input pair
    W_st=5.0,  L_st=1.0,    # M6..M9   steering devices
    W_mir=5.0, L_mir=1.0,   # M1, M4   PMOS mirror
    W_tail=5.0, L_tail=1.0, # M5       tail
    vbias=0.61, vin_cm=0.9, vctrl_cm=1.15, vdd=1.8,   # vctrl_cm re-centred after the n-well fix
    corner="tt", temp=27.0,
    pmos_body="vdd",        # "vdd" = wells tied to supply (correct); "float" = original bug
)

def _geom(W):
    """xschem-equivalent junction geometry for nf=1 (SKY130 diff extension 0.29 um)."""
    return (f"ad={0.29*W:.6g} as={0.29*W:.6g} pd={2*W+0.58:.6g} ps={2*W+0.58:.6g} "
            f"nrd={0.29/W:.6g} nrs={0.29/W:.6g} sa=0 sb=0 sd=0 mult=1")

def _bias(d: dict) -> str:
    """Tail bias. Default: fixed gate voltage d['vbias'] (the 9T baseline). With d['iref'] set: an external
    reference current into a diode-connected NMOS (M12) sized W_ref/L_ref (default = the tail's size), so the
    tail and the keep-alive sinks become ratioed mirrors of iref and track it over process and temperature."""
    if not d.get("iref"):
        return f"Vbias vbias 0 DC {d['vbias']}\n"
    n = "sky130_fd_pr__nfet_01v8"
    W, L = d.get("W_ref", d["W_tail"]), d.get("L_ref", d["L_tail"])
    return f"Iref vdd vbias DC {d['iref']}\nXM12 vbias vbias 0 0 {n} L={L} W={W} nf=1 {_geom(W)}\n"

def _keepalive(d: dict) -> str:
    """Optional keep-alive sinks (M10 at the mirror node, M11 at the output), gate on the tail bias so
    their current is a fixed ratio of the tail current. W_k = 0 (default) gives the original 9T core."""
    if not d.get("W_k"):
        return ""
    n, L, W = "sky130_fd_pr__nfet_01v8", d.get("L_k", 1.0), d["W_k"]
    return (f"XM10 net4  vbias 0 0 {n} L={L} W={W} nf=1 {_geom(W)}\n"
            f"XM11 v_out vbias 0 0 {n} L={L} W={W} nf=1 {_geom(W)}\n")

def circuit(p: dict) -> str:
    """Netlist of the 9-transistor core + bias/stimulus sources. Node names follow
    the xschem netlist: net5=tail, net2=node_A, net3=node_B, net4=mirror node."""
    pb = "vdd" if p["pmos_body"] == "vdd" else "nwell_float"
    n, pf = "sky130_fd_pr__nfet_01v8", "sky130_fd_pr__pfet_01v8"
    d = p
    return f"""
.lib {PDK_LIB} {d['corner']}
{SIM_OPTS}
.temp {d['temp']}
VDD   vdd 0 {d['vdd']}
XM1 net4  net4    vdd  {pb} {pf} L={d['L_mir']} W={d['W_mir']} nf=1 {_geom(d['W_mir'])}
XM4 v_out net4    vdd  {pb} {pf} L={d['L_mir']} W={d['W_mir']} nf=1 {_geom(d['W_mir'])}
XM2 net2  vin_p   net5 0 {n} L={d['L_in']} W={d['W_in']} nf=1 {_geom(d['W_in'])}
XM3 net3  vin_n   net5 0 {n} L={d['L_in']} W={d['W_in']} nf=1 {_geom(d['W_in'])}
XM5 net5  vbias   0    0 {n} L={d['L_tail']} W={d['W_tail']} nf=1 {_geom(d['W_tail'])}
XM6 net4  vctrl_p net2 0 {n} L={d['L_st']} W={d['W_st']} nf=1 {_geom(d['W_st'])}
XM7 vdd   vctrl_n net2 0 {n} L={d['L_st']} W={d['W_st']} nf=1 {_geom(d['W_st'])}
XM8 vdd   vctrl_n net3 0 {n} L={d['L_st']} W={d['W_st']} nf=1 {_geom(d['W_st'])}
XM9 v_out vctrl_p net3 0 {n} L={d['L_st']} W={d['W_st']} nf=1 {_geom(d['W_st'])}
{_keepalive(d)}{_bias(d)}Vid   vid   0 DC 0 AC 1
Bvinp vin_p 0 V = {d['vin_cm']} + V(vid)/2
Bvinn vin_n 0 V = {d['vin_cm']} - V(vid)/2
Vctrl vctrl 0 DC 0
Bvcp  vctrl_p 0 V = {d['vctrl_cm']} + V(vctrl)/2
Bvcn  vctrl_n 0 V = {d['vctrl_cm']} - V(vctrl)/2
Itest 0 v_out DC 0 AC 0
"""

def run(deck: str, tag: str = "deck") -> str:
    """Run ngspice in batch mode; return stdout. Raises with the log tail on error."""
    f = WORK / f"{tag}.cir"
    f.write_text(deck + "\n.end\n")
    r = subprocess.run(["ngspice", "-b", f.name], cwd=WORK, capture_output=True, text=True, timeout=1800)
    out = r.stdout + r.stderr
    bad = [l for l in out.splitlines() if re.search(r"(?i)\berror\b|singular|timestep too small", l)
           and "warning" not in l.lower()]
    if r.returncode != 0 or bad:
        raise RuntimeError(f"ngspice failed ({tag}):\n" + "\n".join(out.splitlines()[-25:]))
    return out

_NUM = r"([-+]?\d*\.?\d+(?:[eE][-+]?\d+)?)"
def parse_print(out: str) -> dict:
    """Parse 'name = value' lines produced by ngspice `print`."""
    res = {}
    for m in re.finditer(r"^\s*(\S+)\s*=\s*" + _NUM + r"\s*$", out, re.M):
        res[m.group(1).lower()] = float(m.group(2))
    return res

def dev(name: str, par: str) -> str:
    kind = "pfet" if name in ("m1", "m4") else "nfet"
    return f"@m.x{name}.msky130_fd_pr__{kind}_01v8[{par}]"

# --------------------------------------------------------------------------- analyses
OP_PROBES = [("v_out", "v(v_out)"), ("v_mir", "v(net4)"), ("v_tail", "v(net5)"),
             ("v_A", "v(net2)"), ("v_B", "v(net3)"), ("v_nwell", None)]
DEV_PROBES = {
    "m1": ["id", "gm", "gds", "vgs", "vds", "vth"], "m4": ["id", "gm", "gds", "vds"],
    "m2": ["id", "gm", "gds", "vgs", "vds", "vth"], "m3": ["id", "gm", "gds", "vds"],
    "m5": ["id", "gm", "vds"],
    "m6": ["id", "gm", "gds", "vds"], "m7": ["id", "gm", "vds"],
    "m8": ["id", "gm", "vds"], "m9": ["id", "gm", "gds", "vds", "vgs", "vth"],
}

def characterise(p: dict, vctrl: float, f_lo: float = 100.0) -> dict:
    """Operating point + low-frequency gain + output resistance at one Vctrl.
    Gain: Vid AC 1, Itest AC 0.  Rout: Vid AC 0, Itest AC 1 A -> |v_out| in ohms."""
    lines = []
    for name, expr in OP_PROBES:
        if expr: lines.append(f"print {expr}")
    if p["pmos_body"] != "vdd": lines.append("print v(nwell_float)")
    for d_, pars in DEV_PROBES.items():
        for par in pars:
            lines.append(f"print {dev(d_, par)}")
    ctrl = f"""
.control
alter vctrl dc = {vctrl}
op
{chr(10).join(lines)}
let isupply = -i(vdd)
print isupply
alter @vid[acmag] = 1
alter @itest[acmag] = 0
ac lin 1 {f_lo} {f_lo}
let av = vm(v_out)
print av
alter @vid[acmag] = 0
alter @itest[acmag] = 1
ac lin 1 {f_lo} {f_lo}
let rout = vm(v_out)
print rout
.endc"""
    out = run(circuit(p) + ctrl, "char")
    r = parse_print(out)
    res = {k: r[e.lower()] for k, e in OP_PROBES if e and e.lower() in r}
    if "v(nwell_float)" in r: res["v_nwell"] = r["v(nwell_float)"]
    for d_, pars in DEV_PROBES.items():
        for par in pars:
            res[f"{d_}_{par}"] = abs(r[dev(d_, par).lower()]) if par in ("id",) else r[dev(d_, par).lower()]
    res["av"], res["rout"] = r["av"], r["rout"]
    res["av_db"] = 20 * math.log10(res["av"])
    res["alpha"] = res["m6_id"] / (res["m6_id"] + res["m7_id"])
    res["gm_model"] = res["alpha"] * res["m2_gm"]
    res["gm_delivered"] = res["av"] / res["rout"]
    res["delivery"] = res["gm_delivered"] / res["gm_model"]
    res["i_tot"] = r["isupply"]          # total supply current: tail, plus keep-alive sinks and reference branch
    res["power"] = p["vdd"] * res["i_tot"]
    res["vctrl"] = vctrl
    return res

def gain_curve(p: dict, vctrls, f_lo: float = 100.0) -> np.ndarray:
    """Low-frequency |Av| (V/V) at each Vctrl, from .ac (exact linearisation)."""
    body = "\n".join(f"alter vctrl dc = {v}\nac lin 1 {f_lo} {f_lo}\nlet g{i} = vm(v_out)\nprint g{i}"
                     for i, v in enumerate(vctrls))
    out = run(circuit(p) + f"\n.control\n{body}\n.endc", "gaincurve")
    r = parse_print(out)
    return np.array([r[f"g{i}"] for i in range(len(vctrls))])

def bandwidth(p: dict, vctrl: float, CL: float = 1e-12) -> dict:
    """f_-3dB with a load capacitor on v_out."""
    deck = circuit(p) + f"CL v_out 0 {CL}\n" + f"""
.control
set wr_singlescale
set wr_vecnames
alter vctrl dc = {vctrl}
ac dec 40 1 100meg
let mag = vm(v_out)
wrdata {WORK}/bw.txt mag
.endc"""
    run(deck, "bw")
    d = np.loadtxt(WORK / "bw.txt", skiprows=1)
    f, m = d[:, 0], d[:, -1]
    a0 = m[0]; tgt = a0 / math.sqrt(2)
    i = int(np.argmax(m < tgt))
    if i == 0: return dict(av_lf=a0, f3db=float("nan"), gbw=float("nan"), vctrl=vctrl, CL=CL)
    # log-log interpolation between the bracketing points; abscissa must be increasing for np.interp
    x = np.log([m[i], m[i-1]]); y = np.log([f[i], f[i-1]])
    f3 = float(np.exp(np.interp(np.log(tgt), x, y)))
    return dict(av_lf=a0, f3db=f3, gbw=a0 * f3, vctrl=vctrl, CL=CL)

def noise(p: dict, vctrl: float, f1: float = 20.0, f2: float = 20e3) -> dict:
    """Input-referred noise (differential input), integrated over [f1, f2]."""
    deck = circuit(p) + f"""
.control
set wr_singlescale
set wr_vecnames
alter vctrl dc = {vctrl}
noise v(v_out) vid dec 40 1 1meg
setplot noise1
wrdata {WORK}/nz.txt inoise_spectrum
.endc"""
    run(deck, "noise")
    d = np.loadtxt(WORK / "nz.txt", skiprows=1)
    f, vn = d[:, 0], d[:, -1]                      # V/sqrt(Hz)
    m = (f >= f1) & (f <= f2)
    vrms = math.sqrt(_trapz(vn[m] ** 2, f[m]))
    return dict(f=f, vn=vn, vn_1k=float(np.interp(1e3, f, vn)), vn_10k=float(np.interp(1e4, f, vn)),
                vrms=vrms, vctrl=vctrl)

def nef(vrms: float, i_tot: float, bw: float, T: float = 300.15) -> float:
    UT = K_B * T / Q
    return vrms * math.sqrt(2 * i_tot / (math.pi * UT * 4 * K_B * T * bw))

def thd(p: dict, vctrl: float, vin_pk: float, f0: float = 1e3, ncyc: int = 12, nh: int = 5) -> dict:
    """THD of v_out for a differential sine of peak amplitude vin_pk (V).
    The mirror node has a pole-zero doublet at a few Hz, so a short transient is not fully settled.
    Instead of a plain Fourier transform, the last 8 periods are fitted to harmonics 1..nh of f0 plus a
    cubic trend; the trend absorbs slow settling, which would otherwise leak into every harmonic."""
    tstop = ncyc / f0; tstep = 1 / (f0 * 200)
    deck = circuit(p).replace("Vid   vid   0 DC 0 AC 1",
                              f"Vid   vid   0 DC 0 SIN(0 {vin_pk} {f0})") + f"""
.control
set wr_singlescale
set wr_vecnames
alter vctrl dc = {vctrl}
tran {tstep} {tstop} 0 {tstep}
linearize v(v_out)
wrdata {WORK}/thd.txt v(v_out)
.endc"""
    run(deck, "thd")
    d = np.loadtxt(WORK / "thd.txt", skiprows=1); t, v = d[:, 0], d[:, -1]
    m = t >= tstop - 8 / f0; t, v = t[m], v[m]; tc = (t - t.mean()) / (t.max() - t.min())
    cols = [tc ** k for k in range(4)]
    for h in range(1, nh + 1):
        cols += [np.sin(2 * np.pi * h * f0 * t), np.cos(2 * np.pi * h * f0 * t)]
    coef = np.linalg.lstsq(np.column_stack(cols), v, rcond=None)[0][4:]
    amp = np.hypot(coef[0::2], coef[1::2])
    return dict(thd_pct=float(100 * np.sqrt(np.sum(amp[1:] ** 2)) / amp[0]), vin_pk=vin_pk, vctrl=vctrl,
                vout_fund_pk=float(amp[0]))

def swing_at_thd(p: dict, vctrl: float, av: float, thd_limit: float = 1.0,
                 vout_grid=(0.01, 0.02, 0.03, 0.04, 0.05, 0.075, 0.1, 0.15, 0.2, 0.3, 0.4, 0.5, 0.6)) -> dict:
    """Output amplitude (peak) at which THD reaches thd_limit.

    Scans the output level upward; at the first level that fails, the crossing is interpolated between it and
    the last passing level assuming THD ~ amplitude**k over that step (k fitted from the two points). If even
    the smallest level fails, THD ~ amplitude is assumed. Interpolating removes the coarse quantisation of a
    pass/fail grid, which otherwise exaggerates differences between designs."""
    rows, prev = [], None
    for vo in vout_grid:
        r = thd(p, vctrl, vo / av); rows.append(r)
        t1 = r["thd_pct"]
        if t1 > thd_limit:
            if prev is None:
                best = vo * thd_limit / t1
            else:
                v0, t0 = prev
                k = math.log(t1 / t0) / math.log(vo / v0) if (t1 > t0 > 0) else 1.0
                best = v0 * (thd_limit / t0) ** (1.0 / k) if k > 0.2 else v0
                best = min(max(best, v0), vo)
            return dict(vout_pk_max=float(best), rows=rows, vctrl=vctrl, interpolated=True)
        prev = (vo, t1)
    return dict(vout_pk_max=float(vout_grid[-1]), rows=rows, vctrl=vctrl, interpolated=False)
