#!/usr/bin/env python3
"""Generate exact fixed-size views of the same Phase 2 fabric; never overwrite evidence."""
import argparse
from datetime import datetime, timezone
import hashlib
import json
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[1]
SIZES = (2, 4, 8)


def render_wrapper(array_size, physical=False):
    """Return deterministic thin-wrapper RTL; neither view changes the PE fabric."""
    if type(array_size) is not int or array_size not in SIZES:
        raise ValueError('array_size must be one of 2, 4, 8')
    lanes = array_size
    cells = array_size * array_size
    top = f'phase2_core_{array_size}' if physical else 'phase2_sim_top'
    ports = [
        '    input wire clk', '    input wire rst', '    input wire clear',
        f'    input wire [{cells - 1}:0] tile_mask',
        f'    input wire [{8 * lanes - 1}:0] a_boundary',
        f'    input wire [{8 * lanes - 1}:0] b_boundary',
        f'    input wire [{lanes - 1}:0] a_valid',
        f'    input wire [{lanes - 1}:0] b_valid',
        f'    input wire [{lanes - 1}:0] a_last',
        f'    input wire [{lanes - 1}:0] b_last',
    ]
    if not physical:
        ports.extend([
            f'    output wire [{32 * cells - 1}:0] accumulators',
            f'    output wire [{cells - 1}:0] result_valid',
            f'    output wire [{cells - 1}:0] active_mask',
        ])
    ports.append('    output wire tile_done')
    lines = [
        '// Generated by scripts/generate_phase2_wrappers.py; do not hand-edit.',
        f'// Fixed ARRAY_SIZE={array_size}; all datapath behavior is in systolic_array/gemm_pe.',
        f'module {top} (', ',\n'.join(ports), ');',
    ]
    if physical:
        lines.extend([
            f'    (* keep = 1 *) wire [{32 * cells - 1}:0] retained_accumulators;',
            f'    (* keep = 1 *) wire [{cells - 1}:0] retained_result_valid;',
            f'    wire [{cells - 1}:0] retained_active_mask;',
        ])
    lines.extend([
        f'    (* keep = 1 *) systolic_array #(.ARRAY_SIZE({array_size})) core (',
        '        .clk(clk), .rst(rst), .clear(clear), .tile_mask(tile_mask),',
        '        .a_boundary(a_boundary), .b_boundary(b_boundary),',
        '        .a_valid(a_valid), .b_valid(b_valid), .a_last(a_last), .b_last(b_last),',
        f'        .accumulators({"retained_accumulators" if physical else "accumulators"}),',
        f'        .result_valid({"retained_result_valid" if physical else "result_valid"}),',
        f'        .active_mask({"retained_active_mask" if physical else "active_mask"}),',
        '        .tile_done(tile_done)', '    );', 'endmodule', '',
    ])
    return '\n'.join(lines)


def sha256(path):
    return hashlib.sha256(Path(path).read_bytes()).hexdigest()


def write_json(path, value):
    Path(path).write_text(json.dumps(value, indent=2, sort_keys=True) + '\n',
                          encoding='utf-8', newline='\n')


def generate(output_root):
    output_root = Path(output_root).resolve()
    raw_root = (ROOT / 'results/raw/phase2').resolve()
    if not output_root.is_relative_to(raw_root) or output_root == raw_root:
        raise ValueError('Output must be a new child directory under results/raw/phase2')
    output_root.mkdir(parents=True, exist_ok=False)
    generated = []
    for size in SIZES:
        for physical in (False, True):
            kind = 'physical' if physical else 'functional'
            top = f'phase2_core_{size}' if physical else 'phase2_sim_top'
            path = output_root / f's{size}' / kind / f'{top}.sv'
            path.parent.mkdir(parents=True, exist_ok=False)
            path.write_text(render_wrapper(size, physical), encoding='utf-8', newline='\n')
            generated.append({'array_size': size, 'view': kind, 'top_module': top,
                              'path': path.relative_to(ROOT).as_posix(),
                              'sha256': sha256(path), 'size_bytes': path.stat().st_size})
    sources = []
    for name in ('scripts/generate_phase2_wrappers.py', 'rtl/gemm_pe.sv', 'rtl/systolic_array.sv'):
        path = ROOT / name
        sources.append({'path': name, 'sha256': sha256(path), 'size_bytes': path.stat().st_size})
    manifest = {'schema_version': 1, 'array_sizes': list(SIZES), 'sources': sources,
                'generated': generated,
                'physical_observability': 'Only tile_done is exposed; full INT32 accumulator cones '
                                          'are retained by identical keep annotations for each size.'}
    write_json(output_root / 'wrappers.manifest.json', manifest)
    return manifest


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--output-root', type=Path, required=True)
    args = parser.parse_args(argv)
    started = datetime.now(timezone.utc).isoformat()
    try:
        manifest = generate(args.output_root)
    except (ValueError, OSError) as error:
        print(f'PHASE2_WRAPPER_GENERATION_FAIL: {error}', file=sys.stderr)
        return 1
    command = {'argv': [sys.executable, *sys.argv], 'cwd': str(Path.cwd()),
               'started_at': started, 'finished_at': datetime.now(timezone.utc).isoformat(),
               'returncode': 0,
               'manifest': (args.output_root.resolve() / 'wrappers.manifest.json').relative_to(ROOT).as_posix(),
               'manifest_sha256': sha256(args.output_root.resolve() / 'wrappers.manifest.json')}
    write_json(args.output_root.resolve() / 'generation.command.json', command)
    print('PHASE2_WRAPPER_GENERATION_PASS ' + str(len(manifest['generated'])))
    return 0


if __name__ == '__main__':
    sys.exit(main())
