// ---------------------------------------------------------------------------
// twiddle_rom : NTT twiddle-factor table
//
// Holds zeta[k] = to_mont(root^bitreverse(k)) for k in 0..DEPTH-1, in the
// Montgomery domain. Contents are generated by the Python golden model
// (write_twiddle_hex) so the ROM and the reference model are bit-identical.
// Synchronous read, 1-clock latency.
// ---------------------------------------------------------------------------
module twiddle_rom #(
    parameter integer WIDTH = 24,
    parameter integer DEPTH = 256,
    parameter integer AW    = 8,
    parameter INIT_FILE = "twiddle_dilithium.vh"
) (
    input  wire            clk,
    input  wire [AW-1:0]   addr,
    output reg  [WIDTH-1:0] rdata
);
    reg [WIDTH-1:0] mem [0:DEPTH-1];

    // Contents come from a generated include file of `mem[i] = ...;` assignments.
    // Using a compile-time `include (not runtime $readmemh) makes the ROM
    // independent of the simulator/OpenLane working directory. The include is
    // resolved through the source include path (SRC), so it works everywhere.
    initial begin
        `include "twiddle_dilithium.vh"
    end

    always @(posedge clk) begin
        rdata <= mem[addr];
    end
endmodule
